// Master data for programmatic SEO page generation
// Industries x Locations = hundreds of pages

export interface IndustryInfo {
  slug: string;
  name: string;
  singular: string;
  painPoint: string;
  emergencyType: string;
  avgJobValue: string;
  commonServices: string[];
  missedCallScenarios: string[];
  whyAiHelps: string[];
  industryChallenge: string;
}

export interface CityInfo {
  slug: string;
  name: string;
  state: string;
  region: string;
  population: string;
  neighborhoods: string[];
  localNote: string;
}

export const industries: IndustryInfo[] = [
  { slug: 'plumbers', name: 'Plumbers', singular: 'plumber', painPoint: 'burst pipes at 2 AM', emergencyType: 'burst pipes, sewage backups, and flooding', avgJobValue: '$1,200', commonServices: ['Emergency pipe repair', 'Drain cleaning', 'Water heater installation', 'Sewer line repair', 'Fixture installation', 'Re-piping'], missedCallScenarios: ['A homeowner discovers a burst pipe flooding their basement at 11 PM — they need help now, not tomorrow.', 'A restaurant owner has a backed-up grease trap on Friday night before a busy weekend.', 'A property manager has a water heater leaking in a rental unit with tenants threatening to withhold rent.'], whyAiHelps: ['Jevus detects the word "flooding" or "burst" and immediately escalates with a priority alert to your on-call plumber.', 'Jevus collects the address, problem description, and severity so your tech arrives prepared — no callback needed.', 'Jevus books the appointment directly into ServiceTitan or Housecall Pro, complete with job notes and customer info.'], industryChallenge: 'Plumbing emergencies don\'t follow a schedule. 40% of plumbing calls come after hours, and the difference between a $200 faucet repair and a $5,000 flood restoration is often just 30 minutes of response time.' },
  { slug: 'hvac', name: 'HVAC Companies', singular: 'HVAC company', painPoint: 'AC dying in 98° heat', emergencyType: 'no-heat, no-AC, and carbon monoxide alerts', avgJobValue: '$1,400', commonServices: ['AC repair', 'Heating repair', 'System installation', 'Duct cleaning', 'Maintenance plans', 'Indoor air quality'], missedCallScenarios: ['A family with a newborn calls at midnight because their heat stopped working in January.', 'Three AC units go down in the same condo complex during a July heat wave — the property manager is calling every HVAC company in town.', 'A commercial client\'s server room AC fails and their equipment is overheating.'], whyAiHelps: ['Jevus recognizes "no heat" and "baby in the house" as an emergency and sends a priority alert immediately.', 'Jevus handles all three calls simultaneously while you\'re on a roof replacing a compressor.', 'Jevus captures the equipment brand, model, and age so your tech shows up with the right parts.'], industryChallenge: 'HVAC is the most seasonal trade in home services. In summer and winter, call volume can triple overnight. The companies that answer every call during peak season are the ones that dominate the market year-round.' },
  { slug: 'electricians', name: 'Electricians', singular: 'electrician', painPoint: 'sparking outlets and burning smells', emergencyType: 'electrical fires, power outages, and exposed wiring', avgJobValue: '$950', commonServices: ['Panel upgrades', 'EV charger installation', 'Outlet repair', 'Lighting installation', 'Whole-house rewiring', 'Generator installation'], missedCallScenarios: ['A homeowner smells burning near an outlet and sees brown marks on the wall — they\'re scared of a fire.', 'A new EV owner needs a Level 2 charger installed before their Tesla delivery next week.', 'A commercial property lost power to half the building and tenants are threatening to break their lease.'], whyAiHelps: ['Jevus tells the caller to shut off the circuit breaker and not use that outlet — providing safety guidance while dispatching your tech.', 'Jevus qualifies the EV charger lead with panel info, garage location, and electrical capacity.', 'Jevus flags commercial emergencies separately and routes them to your commercial dispatch team.'], industryChallenge: 'Electrical work has the highest safety stakes of any trade. A missed emergency call isn\'t just lost revenue — it\'s a potential fire hazard. And the growing EV market means high-value installation leads that go to whoever answers first.' },
  { slug: 'roofing', name: 'Roofers', singular: 'roofer', painPoint: 'storm damage on the roof', emergencyType: 'storm damage, leaks, and fallen trees', avgJobValue: '$8,500', commonServices: ['Roof replacement', 'Storm damage repair', 'Leak repair', 'Gutter installation', 'Roof inspection', 'Insurance claims'], missedCallScenarios: ['After a hurricane, 200 homeowners all call in the same 48-hour window — each one a potential $10K+ insurance restoration job.', 'A realtor needs a roof certification for a closing in 5 days.', 'A homeowner wakes up to water dripping through their ceiling from last night\'s storm.'], whyAiHelps: ['Jevus handles unlimited simultaneous calls during storm surges — zero busy signals while every other roofer\'s phone goes to voicemail.', 'Jevus asks about insurance carrier and claim status to prioritize your most valuable leads.', 'Jevus schedules a free inspection and captures photos/damage description from the homeowner.'], industryChallenge: 'Roofing is feast-or-famine. After a major storm, every roofer in the area gets slammed. The ones who capture leads during the 48-hour window after a storm build a pipeline that lasts 6-12 months. The ones who miss those calls watch competitors grow.' },
  { slug: 'pest-control', name: 'Pest Control Companies', singular: 'pest control company', painPoint: 'rats in the attic', emergencyType: 'wildlife intrusions, termite damage, and infestations', avgJobValue: '$450', commonServices: ['Termite treatment', 'Rodent removal', 'Mosquito control', 'Ant treatment', 'Wildlife removal', 'Bed bug treatment'], missedCallScenarios: ['A homeowner finds a snake in their kitchen and is too terrified to sleep until someone comes.', 'A real estate agent needs a termite clearance letter before closing — they\'re calling three companies and hiring whoever answers.', 'A restaurant gets a health department warning for roaches — they need same-day treatment or risk closure.'], whyAiHelps: ['Jevus recognizes "snake" and "in the house" as wildlife emergency and sends an urgent alert to your removal team.', 'Jevus captures the realtor\'s timeline, property address, and scheduling needs for fast turnaround.', 'Jevus flags commercial food service calls as high-priority with compliance urgency noted.'], industryChallenge: 'Pest control is a trust business. The customer who calls with rats in their attic is scared, not shopping around. They hire whoever answers first and sounds competent. Second place gets nothing.' },
  { slug: 'landscaping', name: 'Landscaping Companies', singular: 'landscaper', painPoint: 'an overgrown yard', emergencyType: 'irrigation failures and storm cleanup', avgJobValue: '$350', commonServices: ['Lawn maintenance', 'Landscape design', 'Irrigation repair', 'Hardscaping', 'Tree trimming', 'Sod installation'], missedCallScenarios: ['A homeowner is hosting an outdoor wedding in 3 weeks and needs a complete yard transformation.', 'An HOA board president needs 15 properties maintained starting next month — a $5K/month recurring contract.', 'A sprinkler head blew and is flooding the yard — the homeowner doesn\'t know how to shut off the system.'], whyAiHelps: ['Jevus captures the event date, scope, and budget to flag this as a high-value design job.', 'Jevus identifies the commercial/HOA nature of the lead and routes it to your sales team.', 'Jevus tells the caller where to find their irrigation shutoff valve while scheduling a repair visit.'], industryChallenge: 'Landscaping has the highest recurring revenue potential of any home service. One lawn care customer is worth $200-400/month for years. Missing that first call doesn\'t just lose one job — it loses the entire lifetime value.' },
  { slug: 'garage-door', name: 'Garage Door Companies', singular: 'garage door company', painPoint: 'a door that won\'t open', emergencyType: 'stuck doors, broken springs, and off-track doors', avgJobValue: '$350', commonServices: ['Spring replacement', 'Opener repair', 'New door installation', 'Off-track repair', 'Panel replacement', 'Preventive maintenance'], missedCallScenarios: ['A homeowner\'s car is trapped in the garage at 6:30 AM and they need to get to work.', 'A broken spring sent the door crashing down — the family is afraid to use the garage.', 'A builder needs 12 garage doors installed on a new construction project by end of month.'], whyAiHelps: ['Jevus treats "car trapped" as a same-day emergency and dispatches your closest tech.', 'Jevus advises the family not to attempt repair and keeps children away from the door — building trust.', 'Jevus captures the builder\'s project details, timeline, and contact for your commercial team.'], industryChallenge: 'Garage door calls are almost always urgent — someone\'s car is stuck or a spring broke. These customers don\'t comparison shop. They call one company, and if that company doesn\'t answer, they call the next. Speed is everything.' },
  { slug: 'general-contractors', name: 'General Contractors', singular: 'general contractor', painPoint: 'a kitchen remodel estimate', emergencyType: 'water damage, fire damage, and structural issues', avgJobValue: '$15,000', commonServices: ['Kitchen remodeling', 'Bathroom remodeling', 'Room additions', 'Insurance restoration', 'Commercial buildout', 'Whole-house renovation'], missedCallScenarios: ['A homeowner wants a $60K kitchen remodel and their realtor referred you — but you\'re on a job site all day.', 'An insurance adjuster is calling about a $40K water damage restoration and needs to reach a contractor today.', 'A commercial tenant needs a $25K office buildout completed before their lease starts.'], whyAiHelps: ['Jevus captures the referral source, project scope, budget, and timeline — so you call back armed with everything you need.', 'Jevus flags insurance restoration leads as highest priority with adjuster contact info.', 'Jevus distinguishes commercial from residential and routes to the right team.'], industryChallenge: 'General contracting has the highest per-job revenue of any trade. A single missed call can cost $15,000-60,000. And GCs spend their entire day on job sites where they physically cannot answer the phone. The disconnect between call timing and availability is the biggest revenue leak in the business.' },
];

// Florida cities - Tampa Bay + statewide expansion
export const floridaCities: CityInfo[] = [
  // Tampa Bay (already have standalone pages, these are for cross-pages)
  { slug: 'tampa', name: 'Tampa', state: 'FL', region: 'Tampa Bay', population: '395K+', neighborhoods: ['South Tampa', 'Westchase', 'Carrollwood', 'New Tampa', 'Seminole Heights', 'Hyde Park'], localNote: 'Tampa is the economic engine of the Gulf Coast with massive demand for home services.' },
  { slug: 'st-petersburg', name: 'St. Petersburg', state: 'FL', region: 'Tampa Bay', population: '270K+', neighborhoods: ['Old Northeast', 'Snell Isle', 'Shore Acres', 'Kenwood', 'Gulfport'], localNote: 'St. Pete\'s booming real estate market drives constant demand for home services.' },
  { slug: 'clearwater', name: 'Clearwater', state: 'FL', region: 'Tampa Bay', population: '117K+', neighborhoods: ['Clearwater Beach', 'Countryside', 'East Clearwater', 'Sand Key'], localNote: 'Clearwater\'s mix of beach condos and residential neighborhoods creates year-round demand.' },
  { slug: 'largo', name: 'Largo', state: 'FL', region: 'Tampa Bay', population: '84K+', neighborhoods: ['Largo Central', 'Indian Rocks', 'Oakhurst', 'Belcher'], localNote: 'Jevus AI is headquartered right here in Largo — built for our local community.' },
  { slug: 'seminole', name: 'Seminole', state: 'FL', region: 'Tampa Bay', population: '18K+', neighborhoods: ['Seminole City Center', 'Bay Pines', 'Lake Seminole'], localNote: 'Seminole\'s established neighborhoods create steady demand for home services.' },
  { slug: 'pinellas-park', name: 'Pinellas Park', state: 'FL', region: 'Tampa Bay', population: '53K+', neighborhoods: ['Mainlands', 'Gateway', 'Park Boulevard'], localNote: 'Pinellas Park is a hub for contractors serving the entire Tampa Bay area.' },
  { slug: 'dunedin', name: 'Dunedin', state: 'FL', region: 'Tampa Bay', population: '36K+', neighborhoods: ['Downtown Dunedin', 'Dunedin Causeway', 'Skinner Boulevard'], localNote: 'Dunedin\'s charming downtown and historic homes drive service demand.' },
  { slug: 'palm-harbor', name: 'Palm Harbor', state: 'FL', region: 'Tampa Bay', population: '61K+', neighborhoods: ['Innisbrook', 'East Lake', 'Lansbrook', 'Crystal Beach'], localNote: 'Palm Harbor\'s affluent communities generate high-value service calls.' },
  { slug: 'treasure-island', name: 'Treasure Island', state: 'FL', region: 'Tampa Bay', population: '7K+', neighborhoods: ['Sunset Beach', 'Isle of Capri'], localNote: 'Treasure Island\'s vacation rentals need fast contractor response times.' },
  { slug: 'safety-harbor', name: 'Safety Harbor', state: 'FL', region: 'Tampa Bay', population: '18K+', neighborhoods: ['Downtown Safety Harbor', 'Philippe Park'], localNote: 'Safety Harbor\'s tight-knit community values reliable local contractors.' },
  { slug: 'tarpon-springs', name: 'Tarpon Springs', state: 'FL', region: 'Tampa Bay', population: '26K+', neighborhoods: ['Sponge Docks', 'Sunset Hills', 'Tarpon Shores'], localNote: 'Tarpon Springs\' historic homes and growing neighborhoods need regular service.' },
  { slug: 'oldsmar', name: 'Oldsmar', state: 'FL', region: 'Tampa Bay', population: '15K+', neighborhoods: ['Oldsmar Proper', 'Baywatch', 'Forest Lakes'], localNote: 'Oldsmar sits between Tampa and Clearwater with steady residential demand.' },
  { slug: 'indian-rocks-beach', name: 'Indian Rocks Beach', state: 'FL', region: 'Tampa Bay', population: '4K+', neighborhoods: ['North IRB', 'South IRB'], localNote: 'Indian Rocks Beach\'s coastal properties need specialized service attention.' },
  { slug: 'madeira-beach', name: 'Madeira Beach', state: 'FL', region: 'Tampa Bay', population: '4K+', neighborhoods: ['John\'s Pass', 'Madeira Way'], localNote: 'Madeira Beach\'s tourist-heavy area needs fast, reliable home service response.' },
  { slug: 'brandon', name: 'Brandon', state: 'FL', region: 'Tampa Bay', population: '115K+', neighborhoods: ['Valrico', 'Bloomingdale', 'Riverview'], localNote: 'Brandon is one of Tampa Bay\'s fastest-growing residential areas.' },
  { slug: 'wesley-chapel', name: 'Wesley Chapel', state: 'FL', region: 'Tampa Bay', population: '60K+', neighborhoods: ['Wiregrass', 'Meadow Pointe', 'Seven Oaks'], localNote: 'Wesley Chapel\'s rapid growth means massive demand for home service contractors.' },
  // Central Florida
  { slug: 'orlando', name: 'Orlando', state: 'FL', region: 'Central Florida', population: '315K+', neighborhoods: ['Downtown', 'Winter Park', 'Dr. Phillips', 'Lake Nona', 'Baldwin Park'], localNote: 'Orlando\'s booming population and tourism industry drive massive home service demand.' },
  { slug: 'kissimmee', name: 'Kissimmee', state: 'FL', region: 'Central Florida', population: '82K+', neighborhoods: ['Downtown Kissimmee', 'Poinciana', 'Celebration'], localNote: 'Kissimmee\'s vacation rental market creates year-round contractor demand.' },
  { slug: 'sanford', name: 'Sanford', state: 'FL', region: 'Central Florida', population: '63K+', neighborhoods: ['Historic Downtown', 'Riverwalk', 'Mayfair'], localNote: 'Sanford\'s growing residential areas drive increasing home service needs.' },
  { slug: 'winter-park', name: 'Winter Park', state: 'FL', region: 'Central Florida', population: '31K+', neighborhoods: ['Park Avenue', 'Baldwin Park', 'Hannibal Square'], localNote: 'Winter Park\'s upscale homes generate high-value service appointments.' },
  { slug: 'daytona-beach', name: 'Daytona Beach', state: 'FL', region: 'Central Florida', population: '72K+', neighborhoods: ['Beachside', 'Midtown', 'LPGA'], localNote: 'Daytona Beach\'s coastal properties face unique service challenges.' },
  // South Florida
  { slug: 'miami', name: 'Miami', state: 'FL', region: 'South Florida', population: '450K+', neighborhoods: ['Brickell', 'Coconut Grove', 'Coral Gables', 'Little Havana', 'Wynwood'], localNote: 'Miami is the largest metro in Florida with massive home service demand year-round.' },
  { slug: 'fort-lauderdale', name: 'Fort Lauderdale', state: 'FL', region: 'South Florida', population: '185K+', neighborhoods: ['Las Olas', 'Victoria Park', 'Wilton Manors', 'Coral Ridge'], localNote: 'Fort Lauderdale\'s waterfront properties and condos need constant service attention.' },
  { slug: 'west-palm-beach', name: 'West Palm Beach', state: 'FL', region: 'South Florida', population: '120K+', neighborhoods: ['Downtown', 'Flamingo Park', 'El Cid', 'Northwood'], localNote: 'West Palm Beach\'s affluent communities generate high-value service leads.' },
  { slug: 'boca-raton', name: 'Boca Raton', state: 'FL', region: 'South Florida', population: '100K+', neighborhoods: ['East Boca', 'West Boca', 'Downtown Boca'], localNote: 'Boca Raton\'s premium homes and strict HOAs demand reliable contractors.' },
  { slug: 'pompano-beach', name: 'Pompano Beach', state: 'FL', region: 'South Florida', population: '115K+', neighborhoods: ['Lighthouse Point', 'Palm Aire', 'Pompano Beach Highlands'], localNote: 'Pompano Beach\'s mix of condos and single-family homes drives steady service calls.' },
  { slug: 'hollywood', name: 'Hollywood', state: 'FL', region: 'South Florida', population: '155K+', neighborhoods: ['Hollywood Beach', 'Downtown', 'Emerald Hills'], localNote: 'Hollywood\'s diverse housing stock creates varied home service demand.' },
  { slug: 'coral-springs', name: 'Coral Springs', state: 'FL', region: 'South Florida', population: '135K+', neighborhoods: ['Heron Bay', 'Eagle Trace', 'Wyndham'], localNote: 'Coral Springs\' planned communities generate consistent maintenance demand.' },
  // North Florida
  { slug: 'jacksonville', name: 'Jacksonville', state: 'FL', region: 'North Florida', population: '950K+', neighborhoods: ['San Marco', 'Riverside', 'Avondale', 'Beaches', 'Mandarin', 'Southside'], localNote: 'Jacksonville is the largest city by area in the US with massive service territory for contractors.' },
  { slug: 'st-augustine', name: 'St. Augustine', state: 'FL', region: 'North Florida', population: '15K+', neighborhoods: ['Historic District', 'Vilano Beach', 'Davis Shores'], localNote: 'St. Augustine\'s historic homes need specialized maintenance and careful restoration.' },
  { slug: 'gainesville', name: 'Gainesville', state: 'FL', region: 'North Florida', population: '145K+', neighborhoods: ['Haile Plantation', 'Duck Pond', 'Tioga'], localNote: 'Gainesville\'s university community drives high rental property service demand.' },
  { slug: 'tallahassee', name: 'Tallahassee', state: 'FL', region: 'North Florida', population: '200K+', neighborhoods: ['Midtown', 'Killearn', 'Southwood', 'Betton Hills'], localNote: 'Tallahassee\'s government and university workforce drives stable home service demand.' },
  // Southwest Florida
  { slug: 'sarasota', name: 'Sarasota', state: 'FL', region: 'Southwest Florida', population: '57K+', neighborhoods: ['Downtown', 'Siesta Key', 'Lakewood Ranch', 'Palmer Ranch'], localNote: 'Sarasota\'s luxury homes and coastal properties generate premium service calls.' },
  { slug: 'naples', name: 'Naples', state: 'FL', region: 'Southwest Florida', population: '22K+', neighborhoods: ['Old Naples', 'Park Shore', 'Pelican Bay', 'Golden Gate'], localNote: 'Naples\' affluent community expects top-tier home service with immediate response.' },
  { slug: 'fort-myers', name: 'Fort Myers', state: 'FL', region: 'Southwest Florida', population: '95K+', neighborhoods: ['Downtown', 'McGregor', 'Gateway', 'Lehigh Acres'], localNote: 'Fort Myers\' growing population means increasing demand for home service contractors.' },
  { slug: 'cape-coral', name: 'Cape Coral', state: 'FL', region: 'Southwest Florida', population: '210K+', neighborhoods: ['Southwest Cape', 'Southeast Cape', 'Cape Harbour'], localNote: 'Cape Coral is one of Florida\'s fastest-growing cities with massive contractor demand.' },
  { slug: 'bradenton', name: 'Bradenton', state: 'FL', region: 'Southwest Florida', population: '57K+', neighborhoods: ['Downtown', 'Palma Sola', 'Lakewood Ranch'], localNote: 'Bradenton\'s growing residential areas create steady demand for skilled contractors.' },
  // Space Coast
  { slug: 'melbourne', name: 'Melbourne', state: 'FL', region: 'Space Coast', population: '86K+', neighborhoods: ['Downtown', 'Melbourne Beach', 'Viera', 'West Melbourne'], localNote: 'Melbourne\'s Space Coast location attracts professionals who expect quality home service.' },
  { slug: 'cocoa-beach', name: 'Cocoa Beach', state: 'FL', region: 'Space Coast', population: '12K+', neighborhoods: ['Downtown Cocoa Beach', 'Snug Harbor'], localNote: 'Cocoa Beach\'s coastal properties face unique saltwater corrosion and storm challenges.' },
  // Treasure Coast
  { slug: 'port-st-lucie', name: 'Port St. Lucie', state: 'FL', region: 'Treasure Coast', population: '220K+', neighborhoods: ['Tradition', 'St. Lucie West', 'Torino'], localNote: 'Port St. Lucie is one of Florida\'s fastest-growing cities with booming contractor demand.' },
  // Panhandle
  { slug: 'pensacola', name: 'Pensacola', state: 'FL', region: 'Panhandle', population: '55K+', neighborhoods: ['Downtown', 'East Hill', 'North Hill', 'Perdido Key'], localNote: 'Pensacola\'s Gulf Coast location means hurricane-related service demand.' },
  { slug: 'panama-city', name: 'Panama City', state: 'FL', region: 'Panhandle', population: '37K+', neighborhoods: ['Downtown', 'St. Andrews', 'Lynn Haven'], localNote: 'Panama City\'s post-hurricane rebuilding continues to drive contractor demand.' },
  { slug: 'destin', name: 'Destin', state: 'FL', region: 'Panhandle', population: '14K+', neighborhoods: ['Crystal Beach', 'Holiday Isle', 'Destin Pointe'], localNote: 'Destin\'s vacation rental market requires fast, reliable home service response.' },
];

// Generate industry x city slug
export function industryLocationSlug(industry: IndustryInfo, city: CityInfo): string {
  return `${industry.slug}-${city.slug}`;
}

// Generate all industry x location combinations
export function getAllIndustryLocationPages() {
  const pages: { industry: IndustryInfo; city: CityInfo; slug: string; path: string }[] = [];
  for (const industry of industries) {
    for (const city of floridaCities) {
      const slug = industryLocationSlug(industry, city);
      pages.push({ industry, city, slug, path: `/industries/${slug}` });
    }
  }
  return pages;
}
