import { FeatureData } from './FeaturePage';

export const features: FeatureData[] = [
  {
    slug: 'ai-voice-receptionist',
    name: 'AI Voice Receptionist',
    heroIcon: '🎙️',
    headline: 'An AI Receptionist\nThat Sounds Human',
    subheadline: 'Jevus answers every call with natural, empathetic conversation. Customers can\'t tell it\'s AI — and they don\'t need to.',
    stats: [
      { value: '<1s', label: 'Pickup time' },
      { value: '100%', label: 'Calls answered' },
      { value: '24/7', label: 'Always on' },
      { value: '50+', label: 'Simultaneous calls' },
    ],
    problem: {
      title: 'The problem with missed calls',
      points: [
        '27% of calls to home service businesses go unanswered.',
        '85% of callers who hit voicemail hang up and call someone else.',
        'Hiring a receptionist costs $47K-$62K/year and only covers 40 hours/week.',
        'Traditional answering services charge per minute and just take messages.',
      ],
    },
    solution: {
      title: 'How Jevus AI solves it',
      points: [
        'Answers every call on the first ring — no voicemail, no hold times.',
        'Has a natural conversation that sounds completely human, with background noise.',
        'Understands trade-specific terminology (burst pipes, no heat, panel upgrades).',
        'Works 24/7/365 at a flat monthly rate — no per-minute charges.',
      ],
    },
    howItWorks: [
      { step: 'Customer calls your business', description: 'Jevus picks up instantly on the first ring. The caller hears a natural, friendly voice that greets them by your company name.' },
      { step: 'AI has a real conversation', description: 'Jevus understands their problem, asks clarifying questions, and collects their name, address, and job details — just like a skilled receptionist.' },
      { step: 'Lead gets qualified and booked', description: 'Based on your rules, Jevus books the appointment, sends you a text summary, or escalates emergencies to your on-call tech.' },
    ],
    benefits: [
      { title: 'Sounds completely natural', description: 'Background office noise, natural pauses, empathetic tone. Callers regularly compliment "the receptionist."' },
      { title: 'Unlimited simultaneous calls', description: 'During peak call times, every caller gets an instant answer. No hold music, no busy signals.' },
      { title: 'Trade-specific knowledge', description: 'Jevus understands plumbing emergencies, HVAC terminology, electrical safety, and roofing damage.' },
      { title: 'Learns your business', description: 'Custom-trained on your services, pricing ranges, service area, and how you want calls handled.' },
      { title: 'Always improving', description: 'AI gets smarter with every call, improving qualification accuracy and conversation quality.' },
      { title: 'Flat monthly pricing', description: 'No per-minute charges. No per-call fees. One predictable monthly cost.' },
    ],
    faqs: [
      { question: 'Will callers know they\'re talking to AI?', answer: 'No. Jevus uses advanced voice synthesis with natural cadence, pauses, and background ambient noise. In testing, the vast majority of callers don\'t realize they\'re speaking with AI.' },
      { question: 'Can Jevus handle multiple calls at once?', answer: 'Yes. Unlike a human receptionist, Jevus handles 50+ simultaneous calls. During storm surges or peak season, every caller gets an instant response.' },
      { question: 'What languages does Jevus support?', answer: 'Jevus currently supports English with plans for Spanish support. The AI handles accents and diverse speaking styles naturally.' },
      { question: 'Can I customize what Jevus says?', answer: 'Yes. You control the greeting, company name, qualification questions, service area, and escalation rules. Jevus represents your brand exactly how you want.' },
    ],
    seo: {
      title: 'AI Voice Receptionist for Home Services | 24/7 Call Answering | Jevus AI',
      description: 'AI voice receptionist that sounds human. Jevus answers every call 24/7, has natural conversations, and books appointments for plumbers, HVAC, and electricians.',
      keywords: 'AI voice receptionist, AI phone answering, virtual receptionist AI, AI answering service home services',
    },
  },
  {
    slug: 'appointment-booking',
    name: 'Smart Appointment Booking',
    heroIcon: '📅',
    headline: 'Jobs Booked\nWhile You Work',
    subheadline: 'Jevus books appointments directly into your calendar during the call — with address, job type, and customer details.',
    stats: [
      { value: '3x', label: 'More bookings' },
      { value: '<60s', label: 'Time to book' },
      { value: '0', label: 'Double-bookings' },
      { value: '85%', label: 'Show rate' },
    ],
    problem: {
      title: 'Why you\'re losing bookings',
      points: [
        'Callers who hit voicemail don\'t leave messages — they call someone else.',
        'By the time you call back, they\'ve already booked a competitor.',
        'Answering services take messages but don\'t actually book appointments.',
        'You spend your evenings returning calls instead of resting.',
      ],
    },
    solution: {
      title: 'Jevus books in real-time',
      points: [
        'Checks your calendar availability during the call.',
        'Books the appointment with full job details, address, and customer info.',
        'Sends confirmation to both you and the customer.',
        'Integrates with ServiceTitan, Housecall Pro, Jobber, and Google Calendar.',
      ],
    },
    howItWorks: [
      { step: 'Customer describes their need', description: 'Jevus understands the job type and urgency — leak, AC repair, panel upgrade, etc.' },
      { step: 'AI checks your availability', description: 'Real-time calendar check ensures no double-bookings. Only offers slots you\'re actually free.' },
      { step: 'Appointment confirmed', description: 'Job lands in your calendar with name, address, phone, job type, and notes. You and the customer both get confirmation.' },
    ],
    benefits: [
      { title: 'Direct CRM integration', description: 'Jobs go straight into ServiceTitan, Housecall Pro, Jobber, or Google Calendar — no manual entry.' },
      { title: 'Zero double-bookings', description: 'Jevus checks real-time availability and respects buffer times between appointments.' },
      { title: 'Customer confirmation', description: 'Automatic text confirmation reduces no-shows and builds professional trust.' },
      { title: 'Complete job details', description: 'Every booking includes name, phone, address, job type, issue description, and urgency level.' },
      { title: 'Rescheduling support', description: 'Customers can call back to reschedule, and Jevus handles it without bothering you.' },
      { title: 'Saves 30+ min/day', description: 'Stop spending evenings returning calls and manually booking. Jevus does it during the call.' },
    ],
    faqs: [
      { question: 'Which calendars does Jevus integrate with?', answer: 'ServiceTitan, Housecall Pro, Jobber, Google Calendar, Outlook, and 50+ more via Zapier.' },
      { question: 'Can Jevus respect my scheduling rules?', answer: 'Yes. Set working hours, buffer times, max appointments per day, service area, and more. Jevus follows all your rules.' },
      { question: 'What if I need to block off time?', answer: 'Just block it in your calendar. Jevus sees the block and won\'t book during that time.' },
    ],
    seo: {
      title: 'AI Appointment Booking for Contractors | Auto-Schedule Jobs | Jevus AI',
      description: 'AI books service appointments in real-time during the call. Integrates with ServiceTitan, Housecall Pro, Jobber. Zero double-bookings, full job details.',
      keywords: 'AI appointment booking, auto schedule contractor, AI booking ServiceTitan, smart scheduling home services',
    },
  },
  {
    slug: 'missed-call-text-back',
    name: 'Missed Call Text Back',
    heroIcon: '💬',
    headline: 'Missed a Call?\nJevus Texts Back\nIn Seconds.',
    subheadline: 'Every missed call instantly gets a text: "Sorry we missed you! We\'re calling you right back." Then Jevus calls them.',
    stats: [
      { value: '<5s', label: 'Text sent' },
      { value: '78%', label: 'Recovery rate' },
      { value: '$1,200', label: 'Avg saved job' },
      { value: '24/7', label: 'Always active' },
    ],
    problem: {
      title: 'Missed calls are lost revenue',
      points: [
        '27% of your calls go unanswered when you\'re on a job.',
        '85% of callers won\'t leave a voicemail — they just call someone else.',
        'By the time you see the missed call 30 minutes later, they\'ve booked a competitor.',
        'Your Google Ads spend is wasted on calls you never answer.',
      ],
    },
    solution: {
      title: 'Instant text + callback',
      points: [
        'Within 5 seconds of a missed call, the customer gets an auto-text from your business.',
        'Text says: "Sorry we missed your call! We\'re calling you right back."',
        'Jevus AI then calls them back within seconds and handles the full conversation.',
        'The customer stays engaged instead of Googling your competitor.',
      ],
    },
    howItWorks: [
      { step: 'You miss a call', description: 'You\'re on a ladder, under a sink, or driving. The call goes unanswered.' },
      { step: 'Instant text goes out', description: 'Within 5 seconds, the customer gets a professional text from your business number keeping them engaged.' },
      { step: 'Jevus calls them back', description: 'AI calls them, has a natural conversation, qualifies the lead, and books the job — all before they call someone else.' },
    ],
    benefits: [
      { title: 'Speed to lead', description: '78% of customers hire the first contractor who responds. Jevus makes sure that\'s you.' },
      { title: 'Recover lost revenue', description: 'Most contractors recover $3,000-5,000/month in previously lost jobs.' },
      { title: 'Maximize ad spend', description: 'Every Google Ads click costs money. Jevus ensures those expensive leads actually convert.' },
      { title: 'Professional impression', description: 'Customers get immediate acknowledgment instead of silence — builds trust before you even talk.' },
      { title: 'Works 24/7', description: 'Missed calls at 10 PM get recovered just as fast as missed calls at 10 AM.' },
      { title: 'Customizable messages', description: 'You control the text message content, branding, and tone.' },
    ],
    faqs: [
      { question: 'How fast does the text go out?', answer: 'Within 5 seconds of the missed call. Speed is critical — every second counts before they call someone else.' },
      { question: 'Can I customize the text message?', answer: 'Yes. You write the message, include your business name, and can even add a booking link.' },
      { question: 'Does this work with my existing phone number?', answer: 'Yes. Texts come from your business number so the customer recognizes it.' },
    ],
    seo: {
      title: 'Missed Call Text Back Service for Contractors | Jevus AI',
      description: 'Automatically text back every missed call within 5 seconds, then AI calls them back. Recover $3,000-5,000/month in lost leads.',
      keywords: 'missed call text back, auto text missed call, missed call recovery service, contractor missed call text',
    },
  },
  {
    slug: 'review-automation',
    name: 'Review Automation',
    heroIcon: '⭐',
    headline: 'Turn Every Job\nInto a 5-Star Review',
    subheadline: 'Jevus automatically follows up after every completed job to request a Google review — at the perfect moment.',
    stats: [
      { value: '3x', label: 'More reviews' },
      { value: '4.9', label: 'Avg rating' },
      { value: '72hrs', label: 'Optimal timing' },
      { value: '0', label: 'Effort from you' },
    ],
    problem: { title: 'Why you have fewer reviews than you should', points: ['You do great work but forget to ask for reviews.', 'Asking in person feels awkward and inconsistent.', 'Customers intend to leave a review but forget by the time they get home.', 'Your competitors have 200+ reviews and you have 30 — even though your work is better.'] },
    solution: { title: 'Automated review requests', points: ['After every completed job, Jevus sends a friendly review request at the perfect moment.', 'Includes a direct link to your Google Business Profile — one tap to leave a review.', 'Happy customers get the review request. Unhappy ones get routed to you first.', 'Consistent, automated, and hands-free.'] },
    howItWorks: [
      { step: 'Job marked complete', description: 'When a job is closed in your calendar or CRM, the review sequence triggers automatically.' },
      { step: 'Timed follow-up sent', description: 'Customer gets a friendly text with a direct Google review link — timed for when satisfaction is highest.' },
      { step: 'Reviews accumulate', description: 'Your Google rating climbs, local SEO improves, and new customers trust you faster.' },
    ],
    benefits: [
      { title: 'More reviews, less effort', description: 'Automated follow-ups mean every customer gets asked. No more remembering or feeling awkward.' },
      { title: 'Better Google ranking', description: 'More reviews = higher local search ranking = more organic leads.' },
      { title: 'Sentiment filtering', description: 'Route unhappy customers to you privately before they leave a bad public review.' },
      { title: 'Direct review link', description: 'One-tap review link removes all friction. Customer doesn\'t have to search for your business.' },
      { title: 'Builds trust fast', description: 'New customers see 100+ five-star reviews and choose you over competitors with fewer.' },
      { title: 'Completely hands-free', description: 'Set it once and reviews accumulate on autopilot.' },
    ],
    faqs: [
      { question: 'When does Jevus send the review request?', answer: 'Timing is configurable. Most contractors send 2-24 hours after job completion, when customer satisfaction is highest.' },
      { question: 'What if the customer is unhappy?', answer: 'Jevus can include a sentiment check. Unhappy customers get routed to you directly instead of the public review page.' },
      { question: 'Does this work with Google and Yelp?', answer: 'Primarily optimized for Google reviews since they have the biggest impact on local SEO. Custom links for Yelp and other platforms are also supported.' },
    ],
    seo: {
      title: 'Automated Google Review Requests for Contractors | Jevus AI',
      description: 'Automatically request 5-star Google reviews after every job. More reviews, better ranking, zero effort. Built for home service businesses.',
      keywords: 'automated review requests, Google review automation, contractor review management, 5 star review automation',
    },
  },
  {
    slug: 'lead-qualification',
    name: 'Lead Qualification',
    heroIcon: '🎯',
    headline: 'Know Which Calls\nAre Worth $10K\nBefore You Call Back',
    subheadline: 'Jevus qualifies every caller — job type, urgency, budget, service area — and prioritizes your callback list by value.',
    stats: [
      { value: '2x', label: 'Close rate' },
      { value: '<60s', label: 'Qualification time' },
      { value: '40%', label: 'Calls filtered' },
      { value: '$0', label: 'Wasted drive time' },
    ],
    problem: { title: 'Unqualified calls waste your time', points: ['You drive 30 minutes to an estimate and the customer has a $100 budget for a $2,000 job.', 'Spam calls and solicitors eat up your callback time.', 'Every call gets the same priority — but a $200 fix shouldn\'t get the same urgency as a $15K remodel.', 'Your answering service takes names and numbers, not job details.'] },
    solution: { title: 'AI qualifies before you callback', points: ['Jevus asks the right questions: job type, scope, urgency, service area, timeline.', 'Tags leads as hot (ready to book), warm (comparing), or cold (just browsing).', 'Filters out spam, solicitors, and out-of-area callers automatically.', 'You get a prioritized list so you call the best opportunities first.'] },
    howItWorks: [
      { step: 'Jevus asks smart questions', description: 'During the call, Jevus naturally collects job type, scope, budget range, address, and timeline.' },
      { step: 'Lead gets scored', description: 'Based on your criteria, leads are tagged as hot, warm, or cold. High-value jobs get priority.' },
      { step: 'You get a ranked list', description: 'Wake up to leads sorted by value. $10K kitchen remodel at the top, $50 caulk job at the bottom.' },
    ],
    benefits: [
      { title: 'Prioritized callback list', description: 'Call back the $10K leads first. Don\'t waste prime hours on low-value inquiries.' },
      { title: 'Save time on estimates', description: 'Stop driving to estimates for customers who can\'t afford the job.' },
      { title: 'Filter out waste', description: 'Spam, telemarketers, and out-of-area calls get handled automatically.' },
      { title: 'Better close rates', description: 'Pre-qualified leads close at 2x the rate of cold callbacks.' },
      { title: 'Custom questions', description: 'You set the qualification criteria. Jevus asks exactly what you need to know.' },
      { title: 'Revenue intelligence', description: 'Track which lead sources produce the highest-value customers over time.' },
    ],
    faqs: [
      { question: 'What questions does Jevus ask?', answer: 'You customize them. Common ones: job type, address, urgency, budget range, how they found you. Jevus asks naturally — it doesn\'t feel like a survey.' },
      { question: 'Can Jevus filter out-of-area callers?', answer: 'Yes. Jevus checks the address against your service area and politely redirects callers outside your zone.' },
      { question: 'How does lead scoring work?', answer: 'You define the tiers. Example: emergency + high job value = hot. Routine maintenance + flexible timeline = warm. Price shopping with no timeline = cold.' },
    ],
    seo: {
      title: 'AI Lead Qualification for Contractors | Smart Lead Scoring | Jevus AI',
      description: 'AI qualifies every caller by job type, urgency, and budget. Get a prioritized callback list sorted by value. Stop wasting time on unqualified leads.',
      keywords: 'AI lead qualification, contractor lead scoring, smart lead filtering, AI lead prioritization home services',
    },
  },
  {
    slug: 'sms-alerts',
    name: 'SMS Owner Alerts',
    heroIcon: '🔔',
    headline: 'Every New Job,\nStraight to Your Phone',
    subheadline: 'Get instant text notifications with full call details — name, address, job type, urgency — seconds after every call.',
    stats: [
      { value: '<10s', label: 'Alert delivery' },
      { value: '100%', label: 'Calls summarized' },
      { value: '0', label: 'Voicemails to check' },
      { value: '24/7', label: 'Always notified' },
    ],
    problem: { title: 'You\'re always behind on messages', points: ['You check voicemail at the end of the day and find 8 messages — half are outdated.', 'Answering services email summaries you don\'t see for hours.', 'You forget which customer said what after listening to 6 voicemails in a row.', 'Emergency calls get buried in the same pile as routine inquiries.'] },
    solution: { title: 'Instant, organized notifications', points: ['Text alert within seconds of every call with a complete summary.', 'Includes customer name, phone, address, job type, and urgency level.', 'Emergency calls flagged with URGENT so you see them immediately.', 'Read between jobs — no voicemail checking needed.'] },
    howItWorks: [
      { step: 'Jevus finishes the call', description: 'After qualifying the lead and booking the appointment, Jevus generates a summary.' },
      { step: 'You get a text instantly', description: 'Within seconds: "New Job: Kitchen leak at 4521 Oak Dr. Sarah M. (813) 555-1234. Booked 2-4 PM."' },
      { step: 'You stay informed between jobs', description: 'Glance at your phone between jobs and know exactly what\'s coming next. No voicemail, no email digging.' },
    ],
    benefits: [
      { title: 'Instant awareness', description: 'Know about every new lead within seconds, not hours.' },
      { title: 'Emergency flagging', description: 'Urgent calls get flagged separately so you can prioritize.' },
      { title: 'Complete details', description: 'Name, phone, address, job type, urgency — everything you need in one text.' },
      { title: 'No voicemail', description: 'Never listen to a voicemail again. Every call is summarized in text.' },
      { title: 'Team routing', description: 'Send alerts to different team members based on job type or area.' },
      { title: 'Call recordings', description: 'Link to full call recording included if you want to listen to the conversation.' },
    ],
    faqs: [
      { question: 'How fast do alerts arrive?', answer: 'Typically within 5-10 seconds of the call ending.' },
      { question: 'Can I send alerts to my team?', answer: 'Yes. Route alerts to different people based on job type, time of day, or service area.' },
      { question: 'Do I get a call recording too?', answer: 'Yes. Every alert includes a link to the full call recording and transcript.' },
    ],
    seo: {
      title: 'Instant SMS Alerts for Every Call | Job Notifications | Jevus AI',
      description: 'Get instant text notifications for every call with name, address, job type, and urgency. Emergency calls flagged immediately. Never check voicemail again.',
      keywords: 'SMS call alerts contractor, instant job notifications, call summary text, contractor call alerts',
    },
  },
  {
    slug: 'client-dashboard',
    name: 'Client Dashboard',
    heroIcon: '📊',
    headline: 'Every Call. Every Lead.\nOne Dashboard.',
    subheadline: 'Track calls, conversion rates, revenue captured, and AI performance — all in real-time from your phone or desktop.',
    stats: [
      { value: 'Real-time', label: 'Data updates' },
      { value: '100%', label: 'Calls tracked' },
      { value: 'ROI', label: 'Revenue tracking' },
      { value: 'Mobile', label: 'Access anywhere' },
    ],
    problem: { title: 'You have no visibility into your calls', points: ['You don\'t know how many calls you\'re missing or what they\'re worth.', 'There\'s no way to track which marketing channels drive the best leads.', 'You can\'t tell if your answering service is doing a good job.', 'Revenue attribution is a guess, not a measurement.'] },
    solution: { title: 'Complete call intelligence', points: ['See every call in real-time — answered, missed, booked, emergency.', 'Track revenue by lead source, job type, and time period.', 'Monitor AI performance — qualification accuracy, booking rates, satisfaction.', 'Access from any device, anywhere.'] },
    howItWorks: [
      { step: 'Calls flow through Jevus', description: 'Every call is logged with full details — time, duration, outcome, recording, transcript.' },
      { step: 'Dashboard updates in real-time', description: 'See new calls, bookings, and revenue as they happen. Filter by date, type, or status.' },
      { step: 'Make data-driven decisions', description: 'Know which marketing channels produce the best leads. See your ROI in black and white.' },
    ],
    benefits: [
      { title: 'Real-time visibility', description: 'See calls and bookings as they happen. No waiting for weekly reports.' },
      { title: 'Revenue tracking', description: 'Track exactly how much revenue Jevus captures. See your ROI clearly.' },
      { title: 'Lead source attribution', description: 'Know which channels (Google Ads, SEO, referrals) produce the best leads.' },
      { title: 'Call recordings', description: 'Listen to any call with full transcript. Great for training and quality assurance.' },
      { title: 'Mobile access', description: 'Check your dashboard between jobs from your phone.' },
      { title: 'Monthly reports', description: 'Automated monthly performance reports showing calls, bookings, and revenue.' },
    ],
    faqs: [
      { question: 'Can I access the dashboard on my phone?', answer: 'Yes. The dashboard is fully responsive and works on any device — phone, tablet, or desktop.' },
      { question: 'Does it track revenue?', answer: 'Yes. The dashboard tracks calls, bookings, and estimated revenue based on your average job values.' },
      { question: 'Can my office manager access it?', answer: 'Yes. You can add team members with different access levels.' },
    ],
    seo: {
      title: 'Call Analytics Dashboard for Contractors | Track Every Lead | Jevus AI',
      description: 'Real-time dashboard tracking every call, booking, and revenue captured by your AI receptionist. Revenue attribution, call recordings, and monthly reports.',
      keywords: 'contractor call dashboard, call analytics home services, lead tracking dashboard, AI receptionist analytics',
    },
  },
  {
    slug: 'integrations',
    name: 'Unlimited Integrations',
    heroIcon: '⚡',
    headline: 'Connects to\nEverything You Use',
    subheadline: 'Jevus integrates with ServiceTitan, Housecall Pro, Jobber, Google Calendar, Zapier, and 1,000+ other tools.',
    stats: [
      { value: '1,000+', label: 'Apps supported' },
      { value: '5 min', label: 'Setup time' },
      { value: '0', label: 'Manual data entry' },
      { value: 'Real-time', label: 'Sync speed' },
    ],
    problem: { title: 'Disconnected tools waste time', points: ['Your answering service emails you, then you manually type job details into your CRM.', 'Customer info lives in 5 different places and none of them talk to each other.', 'You spend 30+ minutes/day on data entry instead of billable work.', 'Mistakes happen when you\'re re-entering info from voicemails.'] },
    solution: { title: 'Everything connected automatically', points: ['Jevus writes directly to your CRM — no manual entry needed.', 'Appointments sync instantly with your calendar.', 'Customer details flow to your invoicing, SMS, and marketing tools.', 'Zapier and n8n support connects to 1,000+ additional apps.'] },
    howItWorks: [
      { step: 'Connect your tools', description: 'During setup, link your calendar, CRM, and notification preferences. Takes about 5 minutes.' },
      { step: 'Jevus handles calls', description: 'Every call result — booking, lead details, emergency alert — flows to your connected tools automatically.' },
      { step: 'Zero manual work', description: 'Jobs appear in ServiceTitan, appointments in your calendar, alerts on your phone. All automatic.' },
    ],
    benefits: [
      { title: 'ServiceTitan native', description: 'Jobs and customer records created automatically in ServiceTitan.' },
      { title: 'Housecall Pro sync', description: 'Appointments and leads sync directly to Housecall Pro.' },
      { title: 'Jobber integration', description: 'New jobs and customer profiles pushed to Jobber in real-time.' },
      { title: 'Google Calendar', description: 'Appointments land directly in your Google Calendar with full details.' },
      { title: 'Zapier & n8n', description: 'Connect to 1,000+ apps: Slack, QuickBooks, Mailchimp, and more.' },
      { title: 'Custom webhooks', description: 'Enterprise clients can use custom webhooks for any proprietary system.' },
    ],
    faqs: [
      { question: 'Does Jevus integrate with ServiceTitan?', answer: 'Yes. Jevus creates jobs, customer records, and appointment bookings directly in ServiceTitan.' },
      { question: 'What about Housecall Pro and Jobber?', answer: 'Both fully supported with native integrations. Appointments, leads, and customer info sync automatically.' },
      { question: 'Can I connect custom tools?', answer: 'Yes. Via Zapier, n8n, or custom webhooks, Jevus can connect to virtually any software.' },
    ],
    seo: {
      title: 'AI Receptionist Integrations | ServiceTitan, Housecall Pro, Jobber | Jevus AI',
      description: 'Jevus AI integrates with ServiceTitan, Housecall Pro, Jobber, Google Calendar, Zapier, and 1,000+ tools. Zero manual data entry.',
      keywords: 'AI receptionist integrations, ServiceTitan AI integration, Housecall Pro AI, Jobber AI receptionist',
    },
  },
  {
    slug: 'white-glove-setup',
    name: 'White-Glove Setup',
    heroIcon: '🤝',
    headline: 'We Set Up\nEverything For You',
    subheadline: 'No DIY. No tech headaches. Our team configures your AI receptionist, tests it, and goes live — you just approve.',
    stats: [
      { value: '48hrs', label: 'Time to live' },
      { value: '0', label: 'Tech work for you' },
      { value: '100%', label: 'Done-for-you' },
      { value: '30 min', label: 'Onboarding call' },
    ],
    problem: { title: 'Tech setup kills momentum', points: ['You signed up for a tool but never configured it because it was too complicated.', 'You don\'t have time to learn another dashboard or set up integrations.', 'DIY setup means mistakes — wrong greetings, missed configurations, broken integrations.', 'You\'re a contractor, not an IT person.'] },
    solution: { title: 'We handle everything', points: ['30-minute onboarding call to learn your business, services, and preferences.', 'Our team configures your AI — greeting, qualification questions, escalation rules, integrations.', 'We test the entire system before going live to make sure it\'s perfect.', 'You approve, we flip the switch, and you\'re live.'] },
    howItWorks: [
      { step: '30-minute onboarding call', description: 'We learn your business: services, pricing ranges, service area, how you want calls handled, and your calendar/CRM setup.' },
      { step: 'We build your AI', description: 'Our team configures everything — greeting, scripts, qualification questions, integrations, and escalation rules.' },
      { step: 'Test and go live', description: 'We run test calls, verify integrations work, and get your approval. Then you\'re live, usually within 48 hours.' },
    ],
    benefits: [
      { title: 'Zero tech work', description: 'You don\'t touch a single configuration screen. We handle it all.' },
      { title: 'Expert configuration', description: 'Our team has set up hundreds of AI receptionists. We know what works for each trade.' },
      { title: 'Tested before launch', description: 'We run test calls and verify every integration before your first real call.' },
      { title: 'Ongoing support', description: 'Need to change your greeting or add a new service? Just tell us and we update it.' },
      { title: 'Trade-specific expertise', description: 'We know what plumbers, HVAC techs, and electricians need — we configure accordingly.' },
      { title: 'Fast turnaround', description: 'Most businesses are live within 48 hours of the onboarding call.' },
    ],
    faqs: [
      { question: 'Do I need any technical skills?', answer: 'None. We handle 100% of the setup. All you do is a 30-minute call to tell us about your business.' },
      { question: 'How long until I\'m live?', answer: 'Most businesses are live within 48 hours of the onboarding call.' },
      { question: 'What if I need changes later?', answer: 'Just tell us. We handle all configuration changes — new services, updated hours, different escalation rules. It\'s all included.' },
    ],
    seo: {
      title: 'White-Glove AI Setup for Contractors | Done-For-You | Jevus AI',
      description: 'We set up your entire AI receptionist for you. 30-minute onboarding call, full configuration, testing, and launch — usually within 48 hours.',
      keywords: 'white glove AI setup, done for you AI receptionist, contractor AI setup service, managed AI phone setup',
    },
  },
];
